apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gittrackobjects.faros.pusher.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="ObjectInSync")].status
    name: In Sync
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    priority: 1
    type: date
  group: faros.pusher.com
  names:
    kind: GitTrackObject
    plural: gittrackobjects
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            data:
              description: Data representation of the tracked object
              format: byte
              type: string
            kind:
              description: Kind of the tracked object
              type: string
            name:
              description: Name of the tracked object
              type: string
          required:
          - name
          - kind
          - data
          type: object
        status:
          properties:
            conditions:
              description: Conditions of this object
              items:
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime of this condition
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: LastUpdateTime of this condition
                    format: date-time
                    type: string
                  message:
                    description: Message associated with this condition
                    type: string
                  reason:
                    description: Reason for the current status of this condition
                    type: string
                  status:
                    description: Status of this condition
                    type: string
                  type:
                    description: Type of this condition
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
