apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gittracks.faros.pusher.com
spec:
  group: faros.pusher.com
  names:
    kind: GitTrack
    plural: gittracks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            deployKey:
              description: DeployKey holds a reference to an SSH key needed to access
                the repository.
              properties:
                credType:
                  description: CredType is the type of credential. Accepted values
                    are "SSH", "OAuthToken". Defaults to "SSH".
                  type: string
                key:
                  description: Key is the key within the Secret object that contains
                    the deploy secret
                  type: string
                secretName:
                  description: SecretName is the name of the Secret object containins
                    the key
                  type: string
              required:
              - secretName
              - key
              type: object
            reference:
              description: Reference contains the git reference this GitTrack tracks
              type: string
            repository:
              description: Repository is the git repository URI to clone from
              type: string
            subPath:
              description: SubPath is the subpath within the repository underneath
                which files are considered
              pattern: ^[a-zA-Z0-9/\-.]*$
              type: string
          required:
          - reference
          - repository
          type: object
        status:
          properties:
            conditions:
              description: Conditions are the conditions on this GitTrack
              items:
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime of this condition
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: LastUpdateTime of this condition
                    format: date-time
                    type: string
                  message:
                    description: Message associated with this condition
                    type: string
                  reason:
                    description: Reason for the current status of this condition
                    type: string
                  status:
                    description: Status of this condition
                    type: string
                  type:
                    description: Type of this condition
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            objectsApplied:
              description: ObjectsApplied is the number of k8s objects for which a
                GitTrackObjects was created
              format: int64
              type: integer
            objectsDiscovered:
              description: ObjectsDiscovered is the number of k8s objects found in
                the repository path
              format: int64
              type: integer
            objectsIgnored:
              description: ObjectsIgnored is the number of k8s objects found in the
                repository path for which no GitTrackObject was created
              format: int64
              type: integer
            objectsInSync:
              description: ObjectsInSync is the number of GitTrackObjects that were
                successfully applied to the cluster
              format: int64
              type: integer
          required:
          - objectsDiscovered
          - objectsApplied
          - objectsIgnored
          - objectsInSync
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
